services:
  # Backend Node.js Service
  - type: web
    name: kavachx-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production

  # ML Python Service
  - type: web
    name: kavachx-ml
    runtime: python
    rootDir: ML
    buildCommand: pip install --upgrade pip && pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app
